[package]
name = "CoffeeUI"
version = "0.1.0"
authors = ["David P. Smith"]
edition = "2020"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
rppal = "0.11.3"
framebuffer = "0.2.0"
bmp = "0.5.0"
